#!/bin/bash
#
# zookeeper - Startup script for the Apache Zookeeper service
#
# chkconfig: 35 85 15
# description: A high-performance coordination service for distributed applications.

### BEGIN INIT INFO
# Provides: zookeeper
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Should-Start: $named $time
# Should-Stop: $named $time
# Short-Description: Startup script for the Apache Zookeeper service
# Description: A high-performance coordination service for distributed applications.
### END INIT INFO

exec="{{ zookeeper.home_dir }}/bin/zkServer.sh"
config={{ zookeeper.home_dir }}/conf/zoo.cfg
service_user="{{ zookeeper.user }}"
prog="zookeeper"

[ -e /etc/default/$prog ] && . /etc/default/$prog

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    su --shell /bin/bash $service_user -c "$exec start"
    retval=$?
    echo
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    su --shell /bin/bash $service_user -c "$exec stop"
    retval=$?
    echo
    return $retval
}

status() {
    exec $exec status
}

restart () {
    su --shell /bin/bash $service_user -c "$exec restart"
}

force_reload() {
    restart
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    force-reload|reload)
        restart
        ;;
    status)
        $1
        ;;
    condrestart|try-restart)
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
