# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box_check_update = false

  config.vm.define "mesos-master1" do |datalab|
    datalab.vm.box = "centos/7"
    datalab.vm.hostname = "datalab-mesos-master1.vm"
    datalab.vm.network "private_network", ip:"192.168.33.60"
    datalab.vm.synced_folder "./", "/vagrant", disabled:true
    datalab.vm.provider "virtualbox" do |vb|
      vb.name = "datalab-mesos-master1"
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "mesos-master2" do |datalab|
    datalab.vm.box = "centos/7"
    datalab.vm.hostname = "datalab-mesos-master2.vm"
    datalab.vm.network "private_network", ip:"192.168.33.70"
    datalab.vm.synced_folder "./", "/vagrant", disabled:true
    datalab.vm.provider "virtualbox" do |vb|
      vb.name = "datalab-mesos-master2"
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "mesos-master3" do |datalab|
    datalab.vm.box = "centos/7"
    datalab.vm.hostname = "datalab-mesos-master3.vm"
    datalab.vm.network "private_network", ip:"192.168.33.80"
    datalab.vm.synced_folder "./", "/vagrant", disabled:true
    datalab.vm.provider "virtualbox" do |vb|
      vb.name = "datalab-mesos-master3"
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "mesos-middleware1" do |datalab|
    datalab.vm.box = "centos/7"
    datalab.vm.hostname = "datalab-mesos-middleware1.vm"
    datalab.vm.network "private_network", ip:"192.168.33.84"
    datalab.vm.synced_folder "./", "/vagrant", disabled:true
    datalab.vm.provider "virtualbox" do |vb|
      vb.name = "datalab-mesos-middleware1"
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "mesos-middleware2" do |datalab|
    datalab.vm.box = "centos/7"
    datalab.vm.hostname = "datalab-mesos-middleware2.vm"
    datalab.vm.network "private_network", ip:"192.168.33.85"
    datalab.vm.synced_folder "./", "/vagrant", disabled:true
    datalab.vm.provider "virtualbox" do |vb|
      vb.name = "datalab-mesos-middleware2"
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "mesos-realtime1" do |datalab|
    datalab.vm.box = "centos/7"
    datalab.vm.hostname = "datalab-mesos-realtime1.vm"
    datalab.vm.network "private_network", ip:"192.168.33.86"
    datalab.vm.synced_folder "./", "/vagrant", disabled:true
    datalab.vm.provider "virtualbox" do |vb|
      vb.name = "datalab-mesos-realtime1"
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "mesos-realtime2" do |datalab|
    datalab.vm.box = "centos/7"
    datalab.vm.hostname = "datalab-mesos-realtime2.vm"
    datalab.vm.network "private_network", ip:"192.168.33.87"
    datalab.vm.synced_folder "./", "/vagrant", disabled:true
    datalab.vm.provider "virtualbox" do |vb|
      vb.name = "datalab-mesos-realtime2"
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "mesos-batch1" do |datalab|
    datalab.vm.box = "centos/7"
    datalab.vm.hostname = "datalab-mesos-batch1.vm"
    datalab.vm.network "private_network", ip:"192.168.33.81"
    datalab.vm.synced_folder "./", "/vagrant", disabled:true
    datalab.vm.provider "virtualbox" do |vb|
      vb.name = "datalab-mesos-batch1"
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "mesos-batch2" do |datalab|
    datalab.vm.box = "centos/7"
    datalab.vm.hostname = "datalab-mesos-batch2.vm"
    datalab.vm.network "private_network", ip:"192.168.33.82"
    datalab.vm.synced_folder "./", "/vagrant", disabled:true
    datalab.vm.provider "virtualbox" do |vb|
      vb.name = "datalab-mesos-batch2"
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "mesos-batch3" do |datalab|
    datalab.vm.box = "centos/7"
    datalab.vm.hostname = "datalab-mesos-batch3.vm"
    datalab.vm.network "private_network", ip:"192.168.33.83"
    datalab.vm.synced_folder "./", "/vagrant", disabled:true
    datalab.vm.provider "virtualbox" do |vb|
      vb.name = "datalab-mesos-batch3"
      vb.cpus = 1
      vb.memory = 1024
    end
    datalab.vm.provision :ansible do |ansible|
      ansible.inventory_path = "vagrant-inventory.ini"
      ansible.playbook = "datalab.yml"
      ansible.extra_vars = { user:"vagrant"}
      ansible.sudo = true
      ansible.limit = 'all'
      ansible.verbose = 'vv'
    end
  end

end
